# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
right_format = """
$kubernetes\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$golang\
$helm\
$lua\
$nodejs\
$rust\
$terraform\
$env_var\
$mise\
$sudo\
$shell\
"""

format = """
$directory\
"""

follow_symlinks = false

[git_branch]
style = 'yellow'

[git_commit]
format = '[\($tag\)]($style)'

