# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
right_format = """$git_branch"""
format = """
$directory\
$kubernetes\
$git_commit\
$git_state\
$git_status\
$docker_context\
$golang\
$helm\
$java\
$gradle\
$lua\
$nodejs\
$python\
$rust\
$scala\
$terraform\
$aws\
$env_var\
$mise\
$sudo\
$shell\
"""
follow_symlinks = false

[git_branch]
style = 'yellow'

[git_commit]
format = '[\($tag\)]($style)'

