execute pathogen#infect()
call pathogen#helptags()
syntax on                           " Turn on syntax highlighting
filetype plugin indent on
let mapleader=","
" colorscheme jellybeans
colorscheme gruvbox
set background=dark
" colorscheme solarized8

set timeout timeoutlen=3000 ttimeoutlen=100
set colorcolumn=120
" set nopaste
set termguicolors
set number                          " Show line numbers
set relativenumber                  " Use relative numbers
set autoread                        " Auto Read...Don't bother me when a file changes externally
set swapfile                        " Don't store temp files in cwd
set encoding=utf8                   " Use UTF-8 by default
set incsearch                       " Search as you type
set hlsearch                        " Highlight search matches
set ruler                           " Show row/col and percentage
set ignorecase                      " Ignore case in a pattern
set smartcase                       " If ignorecase is on & search pattern has uppercase letters, it becomes case sensitive
set showmatch                       " Show matching parens and braces
set autoindent                      " Copy indent from previous line
set nocp                            " Don't make Vim try to emulate Vi
set tabstop=2                       " Show existing tab with 4 spaces width
set shiftwidth=2                    " When indenting with '>', use 4 spaces width
set expandtab                       " On pressing tab, insert 4 spaces
set backspace=indent,eol,start      " Allow backspace beyond insertion point
" set clipboard=unnamedplus           " Allow integration with system Clipboard
set wildmenu                        " Visual autocomplete for command menu
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*/target/*,*/.git/*
set hidden                          " Allows switch to another buffer with unsaved changes
set foldmethod=indent               " Enable folding
set foldlevel=99
autocmd filetype crontab setlocal nobackup nowritebackup
" Key re-mapping
source ~/.vim/config/vimkeybindings.vim
" You Complete Me configuration
source ~/.vim/config/vimycm.vim
" Ultisnips configuration
source ~/.vim/config/ultisnips.vim
" Undotree configuration
source ~/.vim/config/undotree.vim
" Ctrlp configuration
source ~/.vim/config/ctrlp.vim

" Language specific config in .vim/after/language.vim


" Change cursor shape between insert and normal mode in iTerm2.app
if $TERM_PROGRAM =~ "iTerm"
    let &t_SI = "\<Esc>]50;CursorShape=1\x7" " Vertical bar in insert mode
    let &t_EI = "\<Esc>]50;CursorShape=0\x7" " Block in normal mode
endif
