vim.cmd [[inoreabbrev STring String]]
vim.cmd [[inoreabbrev ival implicit val]]
vim.cmd [[inoreabbrev idef implicit def]]
vim.cmd [[inoreabbrev kmail clivethescott@gmail.com]]
vim.cmd [[inoreabbrev kpound <C-k>Pd]]
vim.cmd [[inoreabbrev kquid <C-k>Pd]]
vim.cmd [[inoreabbrev keuro <C-k>Eu]]
vim.cmd [[inoreabbrev kpoint <C-k>oo]]
vim.cmd [[inoreabbrev kcopy <C-k>Co]]
